edition = "2021"
version = "Two"
unstable_features = true

blank_lines_upper_bound = 2
combine_control_expr = false
force_multiline_blocks = true
imports_layout = "Vertical"
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
group_imports = "Preserve"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
